name: Clean Dataset

on:
  push:
    branches:
      - main  # Replace 'main' with the name of your main branch

jobs:
  test:
    runs-on: ubuntu-latest  # You can choose the runner platform here

    steps:
      - name: Update packages
        run: sudo apt-get update && sudo apt-get upgrade -y

      - name: Install SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.9  # Replace '3.x' with your Python version

      - name: Install dependencies
        run: |
         pip3 install 'rasa[spacy]'
         pip3 install transformers
         pip3 install pandas
         pip3 install openpyxl
        # pip3 install --upgrade rasa

      #- name: Use Node.js 16
       # uses: actions/setup-node@v3
        #with:
         # node-version: '20'  # Explicitly specify Node.js 16
    
      - name: create output folder
        run: mkdir -p gridresults


        
      - name: Run train
        run: |
            rasa train --config config.yml      --out models
      - name : copy config 1
        run : cp models/*  gridresults/


      - uses: actions/upload-artifact@v3
        with:
          name: fin_model
          path: gridresults